### PR TITLE
Create `babel-preset-fbjs` Package

### PR DESCRIPTION
**Pull request by yungsters**
Sorry for the huge update, but this cleans up a lot of stuff.

First of all, it pulls out the babel configuration into a new package named `babel-preset-fbjs`. The preset is completely compatible with all the new Babel 6 goodness.

I also removed any extraneous package dependencies and upgraded most of the rest.

Finally, I cleaned up all of the lint errors and warnings, updated some copyright headers.

**Test Plan:**
```
(cd babel-preset; npm install; npm link)
(cd scripts; npm link babel-preset-fbjs; npm install; npm link)
(npm link babel-preset-fbjs; npm link fbjs-scripts; npm install)
npm test
npm run test-plugins
npm run typecheck
npm run lint
```

### CODE REVIEW

**Comment by zpao** [comment]
After a quick look this mostly seems fine. I might have some more comments but the big thing is that I'll want to ship fbjs-scripts 0.6 final first since this will be a breaking change from what we've shipped there and a few projects are using that. I'll look more closely and try to do that tomorrow so we aren't blocked.

**Comment by cpojer** [comment]
What's the status of this? I'd like to get this in and then update Jest to potentially use babel-jest?

**Comment by zpao** [comment]
I failed at "tomorrow" at then went on vacation :) I'll look today,

**Comment by yungsters** [comment]
I think we're just waiting for a new version of **fbjs** to be published. After that, I think @zpao was going to help me review this and maybe run some tests that I don't know about.

**Comment by yungsters** [comment]
Ping.

**Comment by zpao** [comment]
Finally had a chance to look at this. I'm going to merge and do followup work in a new PR (#135) since you're out and this isn't as clean as I first though.

**Pull request closed without merging**
