### PR TITLE
Protect `isEmpty` if `Symbol` is `undefined`

### PR DESCRIPTION
**Pull request by steveluscher**

### CODE REVIEW

**Comment by steveluscher** [comment]
Can someone double check my logic here? I inverted the invariant logic. @yungsters @zpao

**Comment by yungsters** [comment]
Looks good to me.

**Comment by zpao** [comment]
Can you make this change internally too?

**Comment by spicyj** [comment]
I think there's also a Babel transform that could fall back to `@@iterator` automatically for us? Might be misremembering.

**Comment by yungsters** [comment]
Copy the newest version from internal before you merge this.

**Comment by zpao** [comment]
Took @yungsters' diff - 3c3b9d00f283d63f939d75543bf396e8e5a9fd4e

**Comment by steveluscher** [comment]
👍

**Pull request closed without merging**
