### PR TITLE
fix(jest): update cache function for new Jest 27 API

### PR DESCRIPTION
**Pull request by SimenB**
See https://github.com/facebook/jest/pull/10834

### CODE REVIEW

**Comment by SimenB** [comment]
An alternative would be to use https://github.com/facebook/jest/tree/e5816610eaa6d8aa6b4742909d7495be77f8f347/packages/jest-create-cache-key-function which will handle both 26 and 27 version of the signature

**Comment by eps1lon** [comment]
This change is required to use the `react-native` preset in jest 27: https://github.com/reduxjs/react-redux/pull/1733/checks?check_run_id=2820313064#step:6:25

**Comment by gabrielgrover** [comment]
Any news on when this will be merged?

**Comment by enstulen** [comment]
This would be great to have merged!

**Comment by leggomuhgreggo** [comment]
If anyone is here because they're using react-native -- you can use yarn resolutions [as described here](https://github.com/callstack/react-native-testing-library/issues/743#issuecomment-851020892)
```
"resolutions": {
    "react-native/@jest/create-cache-key-function": "^27.0.2"
 }
```

**Comment by leecommamichael** [comment]
I also have this issue after upgrading to Jest 27. I'm up to date on React Native as well.

**Comment by prometheas** [comment]
Same here. Jest 27 breaks my project's CI 😅

**Comment by amq** [comment]
Tagging the latest releaser @GijsWeterings

**Comment by kdnutrien** [comment]
Getting this merged would be excellent.  Breaking us too on a Jest 27 upgrade attempt.

**Comment by GijsWeterings** [comment]
LGTM :)

**Pull request merged**
