### PR TITLE
Try document.scrollingElement first in getDocumentScrollElement

### PR DESCRIPTION
**Pull request by lixiaoyan**
This fixes draft-js#14 for Chrome with "Experimental Web Platform" enabled.
https://github.com/facebook/draft-js/issues/14

### CODE REVIEW

**Comment by lixiaoyan** [comment]
Any updates on this PR?

**Comment by lixiaoyan** [comment]
Seems chrome 61 use `<html>` for scrolling instead of `<body>`.
(`document.scrollingElement` returns `<html>`)
Since chrome 61 is in stabel channel [for all platform](https://googlechrome.github.io/current-versions/), I think this PR should be merged now.

**Comment by keyanzhang** [comment]
@sophiebits seems like you just landed the exact same change internally on Tuesday (https://fburl.com/mygxofn6).

**Comment by sophiebits** [comment]
Yeah!

**Comment by flarnie** [comment]
Thanks again for fixing this @lixiaoyan! Pulling the fix into Draft.js now. :)

**Pull request merged**
