### PR TITLE
Bump devEngine requirement to node >=4

### LINKED ISSUE #128: Increase Requirement to Node v4
What is holding us back from increasing the node version requirement to v4? This will allow us to use a lot of niceties like arrow functions, concise object notation, `Object.assign`, etc.

### PR DESCRIPTION
**Pull request by yungsters**
Closes #128.

After this, we can start going crazy with all the ES2015 features.

### CODE REVIEW

**Comment by zpao** [comment]
👍

*some* of the es2015 features https://nodejs.org/en/docs/es6/

**Comment by yungsters** [comment]
Do you want to merge this before — or after — you publish the next version?

**Comment by zpao** [comment]
Now is fine, it's doesn't affect end users just us.

**Comment by kittens** [comment]
Is `devEngines` actually a thing? Can't find docs for it anywhere.

**Comment by yungsters** [comment]
@kittens It's only a thing if you use https://github.com/facebook/fbjs/blob/master/scripts/node/check-dev-engines.js#L29, heh.

**Comment by zpao** [comment]
Yea, I made it up because the whole node 0.10, 0.12, iojs, 4, 5 mess combined with needing npm2 for some of our flowconfigs meant we had no guarantees anybody was using the right thing and would just get seemingly random failures.

**Pull request merged**
