### PR TITLE
Update CHANGELOG.md for 0.7.0

### PR DESCRIPTION
**Pull request by yungsters**
This is just a placeholder with a list of changes since 0.6.0. We can update / replace it when 0.7.0 is actually published.

cc @zpao

### CODE REVIEW

**Comment by ide** [comment]
@zpao what's your thinking around the timeline for 0.7.0? @skevy's recent fbjs diffs fix some RN issues people are having and allow Relay to work with RN. So the earlier we get a new fbjs release the sooner RN can ship with Relay compat.

**Comment by zpao** [comment]
I meant to followup on this sooner, sorry.

So I guess the question is, how will the cascading of fbjs versions work? I know we updated fbemitter explicitly to get all the RN deps using 0.6. But we aren't going to upgrade React for every fbjs release so that's not a maintainable approach.

**Comment by ide** [comment]
Part of the fbjs and packager changes are to ignore some of the providesModule declarations so I think it'll be fine if there are multiple copies of fbjs. It might be necessary for react and fbemitter to upgrade to 0.7 one time (I don't think so though).

**Comment by spicyj** [comment]
Yeah, starting with RN 0.19 it's fine to have more than one fbjs.

**Comment by martinbigio** [comment]
@zpao, @spicyj we're blocked to land https://github.com/facebook/react-native/pull/5084 up until a new release of fbjs is done (unless we depend on a commit, which I guess is not ideal, right?). There's no rush, just wanted to get an idea when you were planning to release the next version :)

**Comment by skevy** [comment]
Also, it's in the changelog, but https://github.com/facebook/fbjs/pull/100 should be pulled in as well.

**Comment by ide** [comment]
Depending on the commit would actually be a good way to move forward but fbjs has some prepublishing scripts so we need to grab it from npm.

**Comment by Tlvenn** [comment]
@zpao Any update on the timeline ? Sorry to sound impatient but I am kinda excited to see the day where Relay and RN just work together. Thanks in advance.

**Comment by zpao** [comment]
Gonna take a closer look at things today.

**Comment by zpao** [comment]
Pushed 8a84822137b52e8c187a965c0cf22a465f357503 which mostly overlaps with this (but doesn't give it the version number). I think I'll merge #105 and then call that 0.7.

**Comment by skevy** [comment]
Thanks @zpao!

**Pull request closed without merging**
