### PR TITLE
Make DOM utilities work in nested browsing contexts

### PR DESCRIPTION
**Pull request by acusti**
This is a PR of #188 (which was merged into master in October) into the fbjs-0.8.x branch. I’ve been trying to freshen up http://github.com/facebook/react/pull/7936 (wound up having to just create a new branch from master with http://github.com/facebook/react/pull/9184) and make sure it’s ready to go and was noticing that the tests I’d added were hanging, then I realized it’s because the changes in fbjs that the React PR depends on (#188) haven’t been released to the fbjs 0.8.x line.

I also see from #217 that no React 15.x release will upgrade to fbjs 0.9.x because it will entail a breaking change and therefore a new major release. So, can we just merge the updated functionality into fbjs-0.8.x and release a new version there?

Let me know any concerns. The API changes in this PR are 100% compatible with previous versions and the functionality changes were designed to not affect existing code in any way.

### CODE REVIEW

**Comment by zpao** [comment]
Thanks @acusti!

cc @spicyj @gaearon 

I don't think there should be any issue shipping this out in 0.8 but that will mean that React 15.* will get this automatically (which means further small differences between the npm version and the dist version).

Let me know if you have any concerns, otherwise I'll ship this soon.

**Comment by spicyj** [comment]
ack 👍

**Comment by zpao** [comment]
Just published v0.8.10. Thanks again!

**Comment by ramesius** [comment]
Hey, we are seeing failures in our tests where we shallow render our components. Looks like it stems from this change, the removal of the following guard on document: `if (typeof document === 'undefined')`, is causing `ReferenceError: document is not defined`. Whatever is calling this function is not passing in `doc`, and since it is running in node there is no global `document`.

**Comment by danez** [comment]
I have the same here in our tests.

**Comment by acusti** [comment]
Yikes. The test / server-side rendering failures should be resolved by #223. @ramesius thanks for the prompt note and thorough explanation!

**Comment by ramesius** [comment]
@acusti Thanks for the quick turn around on this one.

**Pull request merged**
