### PR TITLE
fix: allow babel-eslint 9 and eslint 5

### PR DESCRIPTION
**Pull request by SimenB**
No breaking changes from the perspective of this package

### CODE REVIEW

**Comment by mjesun** [comment]
@SimenB I guess it needs a release, right? I'll do that on Monday :)

**Comment by SimenB** [comment]
Yes please!

Btw, any reason for https://github.com/facebook/jest/tree/master/packages/eslint-config-fb-strict to live in Jest? If we want those rules in Jest, we should just add it to the config in that repo. If we do want to keep the package, shouldn't it live in this repo?

**Comment by SimenB** [comment]
@mjesun ping 😀

**Comment by mjesun** [comment]
@SimenB I think @jstejada released it yesterday :)

**Comment by SimenB** [comment]
Nope :( https://yarnpkg.com/en/package/eslint-config-fbjs

**Comment by mjesun** [comment]
Released!

**Comment by SimenB** [comment]
woo! I'll update in Jest, we should avoid the peer dep warnings

**Pull request merged**
