### PR TITLE
add setImmediate

### PR DESCRIPTION
**Pull request by zpao**
cc @spicyj

### CODE REVIEW

**Comment by spicyj** [comment]
Kinda sucks that this pollutes but let's go with it until someone complains. lgtm

**Comment by zpao** [comment]
I guess we probably want this in 0.8.x?

**Comment by spicyj** [comment]
Haven't been tracking the versions but that sounds nice.

**Comment by flarnie** [comment]
Thanks for adding this! It enables a fix to be pulled into Github - https://github.com/facebook/draft-js/pull/871

I'm not clear on how versions/releases work for `fbjs`, wondering when we'll be able to use this in Draft.

**Comment by zpao** [comment]
Just published 0.8.7

**Comment by spicyj** [comment]
image

**Pull request merged**
