### PR TITLE
Fix @flow weak usage

### PR DESCRIPTION
**Pull request by bigfootjon**
Flow v0.167 bans "@flow weak". Let's upgrade this module

### CODE REVIEW

**Comment by mroch** [comment]
Maybe we can get back in sync with the internal version: html/shared/fbjs/key-mirror/keyMirrorRecursive.js

I'm on my phone so didn't do a detailed comparison though

**Comment by zpao** [comment]
Yea, things are dramatically out of date here. I've made a couple feeble attempts to get the actual module needs of our projects still using fbjs to trim & update but nothing successful. And we'd need to redo the whole build process too since things have changed so much.

**Comment by bigfootjon** [comment]
I just want Flow to keep passing for fbjs (I'm aware I'm adding to the problem).

Realistically, we should FBShipIt this project from WWW to solve this, but that takes more effort than I have bandwidth for

**Comment by bigfootjon** [comment]
@zpao @mroch looks like we can't just use the latest version from WWW. Any thoughts on using the reverting to the original commit I opened this PR with?

**Pull request merged**
